### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by xjli360** [zjy526223908/TIP-Editor#2]
Wonderful work! But when I run:
`python train_3DGS.py --fp16 --workspace ./res_gaussion/colmap_doll  \
--test --sample \
--bounding_box_path './data/3d_box/doll_glass_bbox.ply' \
--radius_list 1.3  --fovy 50 --phi_list  -45 -30 -15 0 15 30 45  --theta_list 60 75 90
`

i got:

> Namespace(test=True, fp16=True, save_video=False, eval_interval=50, workspace='./res_gaussion/colmap_doll', seed=0, sample=True, radius_list=[1.3], fovy=50.0, 
> phi_list=[-45.0, -30.0, -15.0, 0.0, 15.0, 30.0, 45.0], theta_list=[60.0, 75.0, 90.0], bounding_box_path='./data/3d_box/doll_glass_bbox.ply', iters=30000, lr=0.0005, 
> sh_degree=0, position_lr_init=0.00016, position_lr_final=1.6e-06, position_lr_delay_mult=0.01, position_lr_max_steps=30000, feature_lr=0.0025, opacity_lr=0.05, 
> scaling_lr=0.005, rotation_lr=0.001, percent_dense=0.01, lambda_dssim=0.2, densification_interval=100, opacity_reset_interval=3000, densify_from_iter=500, 
> densify_until_iter=15000, densify_grad_threshold=0.0002, min_opacity=0.005, weight_decay=0, ckpt='latest', data_path='/mnt/d/dataset/data_DTU/dtu_scan105/', 
> if_data_cuda=True, data_type='dtu', initial_points=None, bg_color=None, R_path='./data/colmap_doll/Orient_R.npy', sample_R_path=None, batch_size=1, batch_rays=512, 
> train_resolution_level=1, eval_resolution_level=4, num_work=0, train_batch_type='image', val_batch_type='image', radius_range=[0.15, 0.15], fovy_range=[50, 70], 
> phi_range=[-180, 180], theta_range=[60, 90])
> [INFO] Trainer: df | 2024-04-25_17-27-37 | cuda | fp16 | ./res_gaussion/colmap_doll
> [INFO] Loading latest checkpoint ...
> [WARN] No checkpoint found, model randomly initialized.
> Number of points at initialisation :  1538
> 0it [00:02, ?it/s]
> Traceback (most recent call last):
>   File "/home/tom/fsas/xjli/mmlab/TIP-Editor/train_3DGS.py", line 107, in <module>
>     trainer.sample_mask_views(test_loader, os.path.join(opt.workspace, 'sample_views'))
>   File "/home/tom/fsas/xjli/mmlab/TIP-Editor/models/trainer_3dgs.py", line 401, in sample_mask_views
>     preds, preds_depth, dir = self.test_step(data, if_gui=True)
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tom/fsas/xjli/mmlab/TIP-Editor/models/trainer_3dgs.py", line 280, in test_step
>     outputs = self.model.render(cur_cam, bg_color=self.bg_color)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tom/fsas/xjli/mmlab/TIP-Editor/models/network_3dgaussain.py", line 815, in render
>     rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: not enough values to unpack (expected 4, got 2)

I did not find the same problem in 3DGS issuses. Could you please give me some help? Thanks.

**Comment by zjy526223908** [comment]
use this version of gaussian rasterization
# install gaussian rasterization
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
